### ISSUE TITLE
Error executing

### ISSUE THREAD

**Issue by ghost** [eXascaleInfolab/GenConvNMI#1]
When I tried to run the command I got this error.
libc++abi.dylib: terminating with uncaught exception of type std::domain_error: SystemIsSuspiciuslyFailingTooMuch ctt (maybe your partition is not solvable?)

the input: 
3 5
3 2 7
1 2 5
3
4
5

and:
2 5
1
1 2 5
2
3 2 7
3
3 5
4
5

**Comment by luav** [comment]
Hi @WilliamChristhie,
thanks for the reporting the issue. However, the latest build from the repository works fine there:
```sh
$ ./gecmi tests/clsevalsx/gecmi_crash1_n1.cnl tests/clsevalsx/gecmi_crash1_n2.cnl 
0.340984
```
Probably, you used an older version. I will upload the current build to the "Releases".

Note that the following apps also might be helpful for the clustering evaluations: [OvpNMI](https://github.com/eXascaleInfolab/OvpNMI) and [xmeasures](https://github.com/eXascaleInfolab/xmeasures).
```sh
./onmi tests/clsevalsx/gecmi_crash1_n1.cnl tests/clsevalsx/gecmi_crash1_n2.cnl 
# Average estimated membership in 'tests/clsevalsx/gecmi_crash1_n1.cnl': 0.4231 (11 / 26)
# Average estimated membership in 'tests/clsevalsx/gecmi_crash1_n2.cnl': 0.5357 (15 / 28)
0.80563
```

> There is another issue with the `gecmi` is that I have not normalized the sampling after the speedup optimizations, so it works correctly only to evaluate clusters of approximately the same size. I will fix it, but it is not urgent for me (fixed either since 9c0672 or definitely since the v2.5). I would recommend you to use [OvpNMI](https://github.com/eXascaleInfolab/OvpNMI), where I added also the standard NMI denominator (max divider).

**Comment by luav** [comment]
@WilliamChristhie, please look at the latest [release v2.50](https://github.com/eXascaleInfolab/GenConvNMI/releases/tag/v2.50-Multimatch), where all mentioned issues are fixed and some additional features are added.
